services:
  demo_01_service_02:
    build: .
    ports:
      - "5001:80"
    volumes:
      - .:/code
      - /var/log:/var/log
    links:
      - demo_01_service_02_mongodb
  demo_01_service_02_mongodb:
    image: mongo:5.0
    volumes:
      - demo_01_service_02_mongodb_container:/data/db
    logging:
        driver: none

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

volumes:
  demo_01_service_02_mongodb_container:

networks:
  default:
    name: demo_01
    external: true
  loki:
    name: loki
    external: true